version: '3.8'

networks:
  nginx_net:
    driver: bridge

services:

  nginx:
    image: nginx:1.27.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_net
  
  app:
    image: "node:20-alpine"
    working_dir: /app
    volumes:
      - .:/app
    # ports:
    #   - "8081:8080"
    networks:
      - nginx_net
    command: "npm run dev"
  
  app_replica_1:
    image: "node:20-alpine"
    working_dir: /app
    volumes:
      - .:/app
    # ports:
    #   - "8082:8080"
    networks:
      - nginx_net
    command: "npm run dev"
  
  app_replica_2:
    image: "node:20-alpine"
    working_dir: /app
    volumes:
      - .:/app
    # ports:
    #   - "8083:8080"
    networks:
      - nginx_net
    command: "npm run dev"
  
