name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Repository Name in Lowercase
        id: set-repo-lowercase
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and Push Docker Image
        id: build-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/$"REPO_NAME":${{ github.sha }}

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image
        run: docker pull ${{ secrets.REGISTRY_URL }}/$REPO_NAME:${{ github.sha }}

      - name: Run Tests in Container
        run: |
          docker run --rm ${{ secrets.REGISTRY_URL }}/$REPO_NAME:${{ github.sha }} npm ci
          docker run --rm ${{ secrets.REGISTRY_URL }}/$REPO_NAME:${{ github.sha }} npm test

  deploy:
    name: Deploy Application
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Pull Image
        run: docker pull ${{ secrets.REGISTRY_URL }}/$REPO_NAME:${{ github.sha }}

      - name: Deploy message
        run: |
          docker run --rm ${{ secrets.REGISTRY_URL }}/$REPO_NAME:${{ github.sha }} bash -c "echo 'Application deployed successfully!'"
